---
- hosts: solaris
  remote_user: zasz
  sudo: yes
  gather_facts: False
  tasks:
    - name: comment process line in inittab
      lineinfile: >
        dest=/etc/inittab
	regexp="^h4:(.*)$"
	line="# h4:\1"
	backrefs=yes


    - name: Run init q command
      command: /usr/sbin/init q


    - name: Get processes called sleep
      # awk requires single quotes.
      raw: "ps -A | grep sleep | awk '{print $1}'"
      register: procs


    - name: Show procs going to be killed
      debug: msg="{{ procs.stdout_lines }}"


    - name: Kill procs
      command: /usr/bin/kill -9 {{ item }}
      with_items: procs.stdout_lines



