---
- hosts: solaris
  remote_user: deploy
  sudo: yes
  roles:
   - { role: spike_symlink_release, tags: release }
  tags: spikes10

- hosts: wingroup
  gather_facts: False
  roles:
    - spike_windows_powershell
  tags: spikes20

- hosts: localhostgroup
  gather_facts: False
  tasks:
    - debug: var=answer_to_life_universe_and_everything
  tags: spikes30

